#!/bin/sh
#
# Component versions for the VU-RM-Pipeline
#
# Author: Sophie Arnoult
# Date:   03/04/19
#----------------------------------------------------

# GitHub commit numbers

v_text2naf=fa4178d
v_morphosyntactic_parser_nl=master
v_ixa_pipe_ned=062a983
v_vua_resources=ef75f30
v_svm_wsd=8bb5319
v_vuheideltimewrapper=3762c0e
v_vua_srl_nl=23a18eb
v_vua_srl_dutch_nominal_events=28b9cff
v_multilingual_factuality=cbad484
v_opinion_miner_deluxePP=3d99e85
v_ontotagger=c3796c5
v_eventcoreference=f1de443
v_stanza=v0.2.0
v_e2edutch=v0.2.0
v_stroll=master

# Other sources
v_alpino=Alpino-x86_64-Linux-glibc-2.23-git167-sicstus
v_ixa_pipes=1.1.1
v_dbpedia_spotlight=0.7.1
