#!/bin/bash
while [[ $# > 1 ]]
do
  key="$1"

  case $key in
    -l|--language)
      naflang="$2"
      shift # past argument
    ;;
    -h|--spothost)
      spotlighthost="$2"
      shift # past argument
    ;;
    -p|--spotport)
    spotlightport="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
  esac
  shift # past argument or value
done

if
  [ "$spotlighthost" == "" ]
then
  spotlighthost=localhost
fi
if
  [ "$spotlightport" == "" ]
then
  if
    [ "$naflang" == "nl" ]
  then
      spotlightport=2060
  else
      spotlightport=2020
  fi
fi

exec 6<>/dev/tcp/$spotlighthost/$spotlightport 2>/dev/null
spotlightrunning=$?
exec 6<&-
exec 6>&-

if [ $spotlightrunning -ne 0 ]; then
  if [ ! "$spotlighthost" == "localhost" ]; then
    export spotlighthost="localhost"
    exec 6<>/dev/tcp/$spotlighthost/$spotlightport 2>/dev/null
    spotlightrunning=$?
    exec 6<&-
    exec 6>&-
  fi
fi
if [ $spotlightrunning -ne 0 ]; then
  if [ "$naflang" == "nl" ]; then
    spotresource="nl"
  else
    spotresource="en_2+2"
  fi
  spotlightjar=dbpedia-spotlight-0.7.jar
  local oldd=`pwd`
  cd $resourcesdir
  $scriptsdir/sematree acquire spotlock 0
  gotit=$?
  if [ $gotit == 0 ]; then
    java -jar -Xmx8g $spotlightjar $spotresource \
         http://localhost:$spotlightport/rest  &
    trial=0
    maxtrials=12
    while
      trial=$((trial+1))
      exec 6<>/dev/tcp/$spotlighthost/$spotlightport 2>/dev/null
      spotlightrunning=$?
      exec 6<&-
      exec 6>&-
      
      [ $spotlightrunning -ne 0 ] && [ $trial -le $maxtrials ] 
    do
      sleep 10
    done
    if [ $spotlightrunning -ne 0 ]; then
      export spotlighthost="none"
    fi
    
    $scriptdir/sematree release spotlock
  else
    trial=0
    maxtrials=12
    while
      trial=$((trial+1))
      exec 6<>/dev/tcp/$spotlighthost/$spotlightport 2>/dev/null
      spotlightrunning=$?
      exec 6<&-
      exec 6>&-
      
      [ $spotlightrunning -ne 0 ] && [ $trial -le $maxtrials ] 
    do
      sleep 10
    done
    if [ $spotlightrunning -ne 0 ]; then
      export spotlighthost="none"
    fi
  fi
  cd $oldd
fi
echo $spotlighthost:$spotlightport
